# Generated by Django 5.0.4 on 2024-04-22 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_panel_display_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="panel",
            name="users_with_access",
            field=models.ManyToManyField(
                related_name="panel_access", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
